databases:
  - name: shortlinkdb
    plan: free

services:
  - type: web
    name: shortlink
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn <TON_PROJET>.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shortlinkdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
